MODULE IPE_Precision

  IMPLICIT NONE
  INTEGER, PARAMETER :: sp = SELECTED_REAL_KIND(6,37)
  INTEGER, PARAMETER :: dp = SELECTED_REAL_KIND(15,307)
  INTEGER, PARAMETER :: prec = dp


END MODULE IPE_Precision
